import type { Metadata } from 'next'
import './globals.css'
import { ReduxProvider } from '../app/redux/provider'

export const metadata: Metadata = {
  title: 'Moviex',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><ReduxProvider> {children} </ReduxProvider></body>
    </html>
  )
}
